variables:
  InjectAlmOctaneTasks: 'true'
  OctaneConnectionName: 'ymlQA6s1002first2001'
  ALMOctaneConnection1Workspaces: '2001'
  ALMOctaneLogLevel: 'debug'
  GithubRepositoryConnection: 'DavidMilstein'

jobs:
- job: AlmOctanePipelineStart
  condition: always()
  
- job: C
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: AlmOctanePipelineEnd
  condition: always()
  dependsOn:
  - AlmOctanePipelineStart
  - C
