 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code..
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  InjectAlmOctaneTasks: 'true'
  AlmOctaneConnection1: 'ymlQA6s1002first2001'
  AlmOctaneConnection1Workspaces: '2001'
  ALMOctaneLogLevel: 'debug'
  'system.debug': 'true'

jobs:
- job: AlmOctanePipelineStart
  condition: always()

- job: A
  steps:
  - script: echo Hello, Job A!
    displayName: 'Run a one-line script'
  dependsOn:
  - AlmOctanePipelineStart

- job: B
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: AlmOctanePipelineEnd
  condition: always()
  dependsOn:
  - AlmOctanePipelineStart
  - A
  - B